### ISSUE TITLE
Cards that have pictures as headers don't show the picture when the card is expanded

### ISSUE THREAD

**Issue by PeterJGalbraith** [Xaymar/Trello-Digital-Dark#10]
The "background" property in Layer 1 appears to overwrite the "background-image" property causing the picture in the expanded card to not show. As a potential solution (that has not been thoroughly tested), changing the "background" property to "background-color" appears to fix the issue.

**Comment by Xaymar** [comment]
This seems to have been broken by Trello again, will try to find a fix for it. I hope that they eventually stop messing with the HTML every week.

**Comment by Xaymar** [comment]
This is now fixed.
