### ISSUE TITLE
Powerup buttons are not styled

### ISSUE THREAD

**Issue by JohnFultonian** [Xaymar/Trello-Digital-Dark#2]
<img width="127" alt="powerups" src="https://cloud.githubusercontent.com/assets/21099840/19019870/c0deeb0e-88e1-11e6-9851-a77a3958d466.png">

Powerup buttons do not appear correctly.

**Comment by Xaymar** [comment]
How did you get that menu?

**Comment by Xaymar** [comment]
It was being applied to <a> elements only while it should have applied to all elements using that class. Fix is up now.
