### ISSUE TITLE
Stickers make the cards unreadable

### ISSUE THREAD

**Issue by blackfyre** [Xaymar/Trello-Digital-Dark#4]
Adding stickers to the cards make the contents unreadable 😭 

![fireshot capture 6 - pricecloud_ functional map for vue i_ - https___trello com_b_k7gjortq_price](https://cloud.githubusercontent.com/assets/1991410/23546535/3f9e41e8-0000-11e7-9d78-1aa499556c6b.png)

**Comment by Xaymar** [comment]
Seems like Trello adds a new class to the cards now, I'll fix it.
