### ISSUE TITLE
Card attachment highlight problems

### ISSUE THREAD

**Issue by blackfyre** [Xaymar/Trello-Digital-Dark#5]
Hi!

There's a bit of a coloring issue with card attachements 😄 

![image](https://user-images.githubusercontent.com/1991410/27029223-aec9de9a-4f67-11e7-92d5-b4f6bc468441.png)

When hovering over the attachment, it becomes hard to read 😢

**Comment by Xaymar** [comment]
I didn't know you could attach things to trello cards, it's very likely not even intentionally styled. Will have to figure out how to fix it in a test trello board
