### ISSUE TITLE
Card background reverted to white

### ISSUE THREAD

**Issue by JDiPierro** [Xaymar/Trello-Digital-Dark#6]
![image](https://user-images.githubusercontent.com/867375/27638703-1dd48700-5be2-11e7-9984-1ab85c58e8ed.png)

**Comment by Xaymar** [comment]
Seems like Trello is doing stuff again. Will have to figure out what the new css path is.

**Comment by JDiPierro** [comment]
It looks like `div.list-card` may have changes to `a.list-card`

**Comment by Xaymar** [comment]
Fixed by the commit above.
