### ISSUE TITLE
Background doesn't fill screen

### ISSUE THREAD

**Issue by cmeeren** [Xaymar/Trello-Digital-Dark#9]
As you can see, the background color of the lists doesn't fill the screen.

![image](https://user-images.githubusercontent.com/7766733/36021327-bcadfc94-0d85-11e8-9263-f27b936f11f8.png)

**Comment by Xaymar** [comment]
I don't know what this bug report is about. The list area should not have a different background:
![image](https://user-images.githubusercontent.com/437395/36031301-87bc1064-0daa-11e8-8819-4f6c4ad6896d.png)

**Comment by cmeeren** [comment]
Strange. The behavior on my end is weird; occasionally, the list area background (the upper/lighter one on my screenshot) fills the entire screen (such as when I try to investigate using the F12 developer tools), but other times, such as after a refresh, I observe the split you can see on the screenshot I posted. This is in Firefox, by the way.

**Comment by Xaymar** [comment]
Have so far been unable to reproduce it in Internet Explorer 10/11, Edge, Chrome and Firefox. This is likely an issue with the browser, hardware or driver - the CSS doesn't specify any rules for the list area to be brighter than the background.

**Comment by cmeeren** [comment]
Ok, thanks so much for looking into it!
